# sqlite?????
# ??sqlite???resources???????????????????
# 1.?IDEA?????sqlite???????target???????target/classes/dbs/MySqlite.db????????????target??sqlite??;
# 2.?jar?????sqlite???????????????????????db????window 10???????C:\Users\${???}\AppData\Local\Temp\sqlite-jdbc-tmp-xxxxxxxx.db??
# spring.datasource.url=jdbc:sqlite::resource:dbs/MySqlite.db
# ??sqlite???????
# 1.?IDEA??????????????????????????src???????
# 2.?jar??????????????jar??????
# spring.datasource.url=jdbc:sqlite:dbs/MySqlite.db
# ??sqlite???????
spring.datasource.url=jdbc:sqlite::resources:cms.db
# mapper.xml????
mybatis.mapper-locations=classpath:mappers/*.xml
# spring?jdbc????spring.datasource.url?????driver-class-name???spring.datasource.driver-class-name???????
spring.datasource.driver-class-name=org.sqlite.JDBC
# sqlite????????????????????sqlite??????????????????????
# spring.datasource.username=
# spring.datasource.password=